[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4.1.0"
serde = { version = "1.0.144", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
config = "0.13.2"
chrono = "0.4.22"
uuid = { version = "1.1.2", features = ["v4"] }
tracing = { version = "0.1.36", features = ["log"] }
tracing-subscriber = { version = "0.3.15", features = [
    "env-filter",
    "registry",
] }
tracing-bunyan-formatter = "0.3.3"
tracing-log = "0.1.3"
secrecy = { version = "0.8.0", features = ["serde"] }
tracing-actix-web = "0.6.0"
serde-aux = "4.0.0"
unicode-segmentation = "1.9.0"
validator = "0.16.0"
claim = "0.5.0"
serde_json = "1.0.85"
reqwest = { version = "0.11.12", features = ["json"] }

[dependencies.sqlx]
version = "0.6.1"
default-features = false
features = [
    "runtime-actix-rustls",
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "offline",
]


[dev-dependencies]
once_cell = "1.14.0"
fake = "2.5.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
