#! config/base.yaml
application:
  port: 8000
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "https://api.sendgrid.com"
  sender_email: "devlemon@mail.com"
  authorization_token: "lol"
  timeout_milliseconds: 10000