application:
  host: 0.0.0.0
    base_url: "https://newsletter-92ml7.ondigitalocean.app"
database:
  require_ssl: false
email_client:
  base_url: "https://api.sendgrid.com"
  sender_email: "devlemon@mail.com"